blog/urls.py
from django.urls import path
from blog import views

app_name = 'app'
urlpatterns = [
    path('post/create/', views.PostCreateView.as_view(), name='create_post'),
    path('post/published/', views.PostListView.as_view(), name='post_list'),
    path('post/drafts/', views.PostDraftListView.as_view(), name='draft_list'),
    path('post/detail/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/update/<int:pk>', views.PostUpdateView.as_view(), name='post_update'),
    path('post/delete/<int:pk>', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/publish/<int:pk>', views.post_publish, name = 'publish'),
    path('post/comments/<int:pk>', views.add_comment, name = 'comment'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('otp/verify/', views.otp_verify, name='otp'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('add_profile/', views.add_user_profile, name='add_profile'),
    path('app/', include('blog.urls')),
    path('paytm/', include('payments.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    prof_url = models.URLField()
    prof_pic = models.ImageField(upload_to = 'prof_pics')

    def __str__(self):
        return self.user.username


class Post(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    text = models.TextField()
    created_date = models.DateTimeField(default= timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('index')

    def __str__(self):
        return self.title + str(self.pk) 


class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author =models.CharField(max_length=256, unique=True, blank=False, null=False)
    text = models.TextField()

    def __str__(self):
        return self.author

blog/forms.py
from django import forms
from blog import models

class UserModelForm(forms.ModelForm):

    class Meta():
        model = models.User
        fields = ('username', 'email', 'password')


class UserProfileModelForm(forms.ModelForm):
    class Meta():
        model = models.UserProfile
        fields = ('prof_url', 'prof_pic')

class CommentModelForm(forms.ModelForm):
    class Meta():
        model = models.Comment
        fields = ('author', 'text')

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog import forms
from django.core.mail import send_mail
import random
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from blog import models
from django.utils import timezone
from django.views.generic import (CreateView, UpdateView, 
                                  ListView, DetailView,
                                  DeleteView)

from django.contrib.auth.mixins import LoginRequiredMixin
#################################################################
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
#################################################################
# Create your views here.

def index(request):
    return render(request, 'base.html', {})

user=0
def otp_verify(request):

    otp = request.POST.get('otp')
    uotp = request.POST.get('eotp')

    if otp==uotp:
        user.save()
        return HttpResponse('<h1> Registration Successful </h1>')
    else:
        return HttpResponse('<h1> Otp Verification Failed </h1>')

def register(request):
    if request.method=='POST':
        global user
        user = forms.UserModelForm(request.POST)
        
        otp = random.randint(1111,9999999)
        if user.is_valid():
            pwd = request.POST.get('password')
            user = user.save(commit=False)
            user.set_password(pwd)
            mail = request.POST.get('email')
            send_mail(
            'OTP',
            f'Here is the otp to complete registration {otp}.',
            settings.EMAIL_HOST_USER,
            [mail],
            fail_silently=False, )

            return render(request, 'register/otp.html', {'otp':otp})
        else:
            print(user.errors)
            return HttpResponse('<h1> Invalid User</h1>')


    else:
        form = forms.UserModelForm()
        return render(request, 'register/register.html', {'form':form})

def user_login(request):
    if request.method=='POST':
        username = request.POST.get('usrname')
        password = request.POST.get('usrpwd')
        user = authenticate(username=username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['usr_login'] = True
                request.session['username'] = username


                return HttpResponseRedirect(reverse('index'))
        else:
            return HttpResponse('<h1>Log in Again </h1>')
    else:
        return render(request, 'register/login.html')


def user_logout(request):
    del request.session['usr_login']
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def add_user_profile(request):

    if request.method == 'POST':
        form = forms.UserProfileModelForm(request.POST, request.FILES)

        if form.is_valid():
            form_obj = form.save(commit=False)
            usr = request.session['username']
            user = models.User.objects.get(username = usr)
            form_obj.user = user

            if 'prof_pic' in request.FILES:
                form_obj.prof_pic = request.FILES['prof_pic']

            form_obj.save()

            return HttpResponse('Profile Added')

    else:
        form = forms.UserProfileModelForm()
        return render(request, 'register/add_profile.html', {'form':form})

class PostCreateView(LoginRequiredMixin, CreateView):
    model = models.Post
    login_url = '/login/'
    fields = ('author', 'title', 'text')
    def form_valid(self, form):
        instance = form.save(commit=False)
        username = self.request.session['username']
        if instance.author.username == username:
            return super().form_valid(form)
        else:
            return HttpResponse('INVALID FORM')

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Post
    login_url = '/login/'
    fields = ( 'title', 'text')

class PostListView(ListView):
    model = models.Post
    
    def get_queryset(self):

        return self.model.objects.filter(published_date__lte = timezone.now()).order_by('-published_date')

class PostDraftListView(LoginRequiredMixin,ListView):
    model = models.Post
    login_url = '/login/'
    paginate_by = 2

    def get_queryset(self):
        username = self.request.session['username']
        user = models.User.objects.get(username=username)
        return self.model.objects.filter(author = user,published_date__isnull = True).order_by('created_date')

    def get_context_data(self, **kwargs):
        context = super(PostDraftListView, self).get_context_data(**kwargs) 
        list_exam = self.model.objects.all() #get all model objects
        paginator = Paginator(list_exam, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)
            
        context['list_exams'] = file_exams
        context['Pagination'] = "This is A Context"
        return context

class PostDetailView(DetailView):
    model = models.Post
    
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Post
    success_url = reverse_lazy('app:post_list')


def post_publish(request, pk):
    post = get_object_or_404(models.Post, pk=pk)

    post.publish()

    return HttpResponseRedirect(reverse('app:post_list'))



def add_comment(request, pk):

    if request.method == 'POST':
        form = forms.CommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)

            comment.post = get_object_or_404(models.Post, pk=pk)
            comment.save()
            return HttpResponseRedirect(reverse('app:post_list'))

    else:
        form = forms.CommentModelForm()
        return render(request, 'blog/comments.html', {'form':form, 'id':pk})

templates/blog/comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'app:comment' id %}" method='POST'>
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" value="Add Comment">
    </form>
</body>
</html>

templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h2>Author: {{object.author.username}}</h2>
        <h2>Title: {{object.title}}</h2>

        <p>{{object.text}}</p>
        <h3>--------------------------------------------------</h3>
    <input type="submit" value="Delete">
    <h3>--------------------------------------------------</h3>
    </form>
</body>
</html>

templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

    {% if not object.published_date %}
    <a href="{% url 'app:publish' object.id %}"> <h1>Publish</h1></a>
    {% endif %}
    <h2>Author: {{object.author.username}}</h2>
    <h2>Title: {{object.title}}</h2>

    <p>{{object.text}}</p>
    <h3>--------------------------------------------------</h3>
    {% if request.session.username == object.author.username%}
    <a href="{% url 'app:post_update' object.id %}"><h2>Update</h2></a>
    <h3>--------------------------------------------------</h3>
    <a href="{% url 'app:post_delete' object.id %}"><h2>Delete</h2></a>
    {% endif %}
    <h3>--------------------------------------------------</h3>

    {% if object.published_date %}
    <a href="{% url 'app:comment' object.id %}"><h1>Add Comment</h1></a>
    {% endif %}


    {% for comment in object.comments.all %}

    <h2><i>{{comment.author}}</i></h2>
    <h2><i>{{comment.text}}</i></h2>

    {% empty %}
    <h3>No Comments Yet</h3>

    {% endfor %}


</body>
</html>

templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {% if form.instance.pk %}
        <input type="submit" value="Update">
        {% else %}
        <input type="submit" value="Create">
        {% endif %}
    </form>
</body>
</html>

templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
    <h2>Title: <a href="{% url 'app:post_detail' object.id %}"> {{object.title}} </a></h2>
    <h3>Author: {{object.author.username}}</h3>
    <h3>--------------------------------------------------------</h3>
    {% endfor %}

<h1>{{Pagination}}</h1>
<h1>Pagination</h1>
        {% if is_paginated %}
        <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
            </li>
        {% endif %}
            <li class="">
                <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
            </li>
        {% if page_obj.has_next %}
            <li>
                <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
            </li>
        {% endif %}
        </ul>
        {% else %}
            <h3>Your File Exam</h3>
            <p>File not yet available</p>
        {% endif %}
</body>
</html>